# Generated by Django 5.1.2 on 2025-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMapp', '0004_customer_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
